### ISSUE TITLE
Issue with objectscript-json-trace-viewer Version Compatibility in Docker Compose Template

### ISSUE THREAD

**Issue by pietrodileo** [intersystems-community/iris-interoperability-template#9]
Hello,

I recently downloaded the template to experiment with containerization in one of my production environments. However, I encountered an error while composing the docker-compose.yml file:

> #0 18.43 ERROR! Could not find satisfactory version of objectscript-json-trace-viewer in any repositories. Required by: interoperability-sample: 1.0.*; objectscript-json-trace-viewer: >=1.1.1 (currently installed, downgrade not permitted)

Currently, the "objectscript-json-trace-viewer" available via zpm is at version 1.1.1 (dated 26 Feb, 2024). I believe the issue can be resolved by modifying the module.xml at:

>         <ModuleReference>
>           <Name>objectscript-json-trace-viewer</Name>
>           <Version>**1.0.***</Version>
>         </ModuleReference>
>

**Comment by evshvarov** [comment]
Fixed
